"""Pantheon 2.0 teaser: score and sound design, synthesised from scratch.

Every sound here is generated by this file with numpy/scipy (no samples, no
recordings), timed from src/timeline.json, the same file the picture reads.

    python3 audio/synth.py            # writes out/audio/{music,sfx,mix}.wav

Mix: -14 LUFS integrated, true peak <= -1 dBTP (4x oversampled), 48 kHz 24-bit.
Stems are written at the mix gain, before the final peak limiter.
"""
import json
import os

import numpy as np
import pyloudnorm as pyln
import soundfile as sf
from scipy.signal import butter, fftconvolve, istft, resample_poly, sosfilt, stft

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TL = json.load(open(os.path.join(ROOT, 'src', 'timeline.json')))
SR = TL['audio']['sampleRate']
DUR = TL['meta']['duration']
N = int(round(SR * DUR))
EV = TL['events']
BEAT = TL['meta']['beat']
rng = np.random.default_rng(708)

# Note frequencies (A4 = 440).
def hz(name):
    names = {'C': -9, 'C#': -8, 'Db': -8, 'D': -7, 'D#': -6, 'Eb': -6, 'E': -5, 'F': -4, 'F#': -3, 'Gb': -3, 'G': -2, 'G#': -1, 'Ab': -1, 'A': 0, 'A#': 1, 'Bb': 1, 'B': 2}
    n, o = name[:-1], int(name[-1])
    return 440.0 * 2 ** ((names[n] + 12 * (o - 4)) / 12)


# ---------- building blocks ----------

def T(sec):
    return np.arange(int(round(sec * SR))) / SR


def stereo():
    return np.zeros((N, 2))


def place(buf, sig, t0, pan=0.0, gain=1.0):
    """Add a mono or stereo signal into buf at t0 seconds, equal-power pan -1..1."""
    i0 = int(round(t0 * SR))
    if sig.ndim == 1:
        a = (pan + 1) * np.pi / 4
        sig = np.stack([sig * np.cos(a), sig * np.sin(a)], axis=1)
    j0, j1 = max(0, i0), min(N, i0 + len(sig))
    if j1 > j0:
        buf[j0:j1] += sig[j0 - i0:j1 - i0] * gain


def sos(kind, f, order=4):
    return butter(order, f, kind, fs=SR, output='sos')


def lp(x, f, o=4): return sosfilt(sos('lowpass', f, o), x, axis=0)
def hp(x, f, o=4): return sosfilt(sos('highpass', f, o), x, axis=0)
def bp(x, lo, hi, o=4): return sosfilt(sos('bandpass', [lo, hi], o), x, axis=0)


def noise(sec):
    return rng.standard_normal(int(round(sec * SR)))


def env_ar(n, a, r, shape=1.0):
    """Attack/release envelope over n samples (a, r in seconds)."""
    t = np.arange(n) / SR
    e = np.minimum(1, t / max(a, 1e-4)) * np.minimum(1, (n / SR - t) / max(r, 1e-4))
    return np.clip(e, 0, 1) ** shape


def smoother(x):
    x = np.clip(x, 0, 1)
    return x * x * x * (x * (x * 6 - 15) + 10)


def tv_filter(x, gain_fn, nper=2048):
    """Time-varying spectral shaping: gain_fn(t[1,frames], f[bins,1]) -> gains."""
    f, tt, Z = stft(x, fs=SR, nperseg=nper, noverlap=nper * 3 // 4)
    G = gain_fn(tt[None, :], f[:, None])
    _, y = istft(Z * G, fs=SR, nperseg=nper, noverlap=nper * 3 // 4)
    out = np.zeros_like(x)
    out[:min(len(x), len(y))] = y[:len(x)]
    return out


def ir(sec, decay, lowcut=8000, seed=1):
    """A synthetic stereo room: decorrelated decaying noise, darker as it fades."""
    r = np.random.default_rng(seed)
    t = T(sec)
    out = []
    for ch in range(2):
        n = r.standard_normal(len(t)) * np.exp(-t / decay)
        n = lp(n, lowcut, 2)
        n[: int(0.012 * SR)] *= np.linspace(0, 1, int(0.012 * SR))
        out.append(n)
    h = np.stack(out, axis=1)
    return h / np.sqrt((h ** 2).sum(axis=0).mean())


def reverb(x, h, wet=0.3):
    """x: (n,2) -> x + wet * (x conv h), length extended by the tail."""
    y = np.stack([fftconvolve(x[:, c], h[:, c]) for c in range(2)], axis=1)
    out = np.zeros_like(y)
    out[:len(x)] = x
    return out + wet * y


def sine_sweep(sec, f0, f1, curve='exp'):
    t = T(sec)
    k = t / sec
    f = f0 * (f1 / f0) ** k if curve == 'exp' else f0 + (f1 - f0) * k
    return np.sin(2 * np.pi * np.cumsum(f) / SR)


# ---------- music ----------

music = stereo()

# 0–3: drone. D1/D2 sines, slow LFO, a breath of filtered noise.
t = T(3.6)
lfo = 0.75 + 0.25 * np.sin(2 * np.pi * 0.23 * t)
drone = (0.55 * np.sin(2 * np.pi * hz('D1') * t) + 0.45 * np.sin(2 * np.pi * hz('D2') * t + 0.6 * np.sin(2 * np.pi * 0.11 * t))) * lfo
drone += 0.35 * lp(noise(3.6), 260, 2)
drone *= env_ar(len(t), 1.2, 0.9)
place(music, drone, 0.0, 0, 0.16)

# 3–16: cold pad on D-A-E-F, detuned saws, slowly opening.
def saw(f, t, phase=0.0):
    # Band-limited enough at these pitches through the low-pass that follows.
    return 2 * ((f * t + phase) % 1.0) - 1


t = T(13.4)
pad = np.zeros((len(t), 2))
for name, g in [('D3', 1.0), ('A3', 0.8), ('E4', 0.55), ('F4', 0.6)]:
    for d, side in [(-7, 0), (0, None), (7, 1)]:
        v = saw(hz(name) * 2 ** (d / 1200), t, rng.random()) * g
        if side is None:
            pad += np.stack([v, v], axis=1) * 0.7
        else:
            pad[:, side] += v
pad = tv_filter(pad[:, 0], lambda tt, f: 1 / (1 + (f / (500 + 700 * smoother(tt / 9.0))) ** 4))[:, None] * [1, 0] + \
      tv_filter(pad[:, 1], lambda tt, f: 1 / (1 + (f / (500 + 700 * smoother(tt / 9.0))) ** 4))[:, None] * [0, 1]
pad *= env_ar(len(t), 2.5, 0.25)[:, None]
# Duck under the card section so the pulse and arpeggio lead.
duck = np.ones(len(t))
k0, k1 = int(9.0 * SR), int(9.6 * SR)
duck[k0:k1] = np.linspace(1, 0.55, k1 - k0)
duck[k1:] = 0.55
pad *= duck[:, None]
place(music, pad, 3.0, 0, 0.035)

# 3–12: muted pulse on every beat.
def thump(f=hz('D2'), dec=0.16, click=0.25):
    t = T(0.5)
    p = np.sin(2 * np.pi * f * t * (1 + 0.5 * np.exp(-t / 0.02))) * np.exp(-t / dec)
    c = hp(noise(0.5), 1500, 2) * np.exp(-t / 0.004) * click
    return p + c


b = 3.0
while b < 12.0 - 1e-6:
    accent = 1.0 if round((b - 3.0) / BEAT) % 4 == 0 else 0.7
    place(music, thump(), b, 0, 0.16 * accent * min(1.0, 0.45 + (b - 3.0) / 4))
    b += BEAT

# 12–16: pulse locked to the card flashes (accelerating), plus a glassy arpeggio.
flash_start = TL['flashes']['start']
flashes = []
tt0 = flash_start
for fr in TL['flashes']['frames']:
    flashes.append(tt0)
    tt0 += fr / TL['meta']['fps']
for i, ft in enumerate(flashes):
    place(music, thump(hz('D2'), 0.12, 0.35), ft, 0, 0.12 + 0.006 * i)


def glass_note(f, dec=0.35):
    t = T(1.2)
    mod = np.sin(2 * np.pi * f * 3.5 * t) * 1.2 * np.exp(-t / 0.08)
    s = np.sin(2 * np.pi * f * t + mod) * np.exp(-t / dec) + 0.3 * np.sin(2 * np.pi * f * 2 * t) * np.exp(-t / (dec * 0.5))
    return s * env_ar(len(t), 0.003, 0.05)


arp = ['D5', 'A5', 'F5', 'A5', 'D6', 'A5', 'F5', 'E5']
step = BEAT / 4
k = 0
x = 12.0
while x < 16.0 - 1e-6:
    level = 0.035 + 0.03 * (x - 12.0) / 4
    place(music, glass_note(hz(arp[k % len(arp)]), 0.28), x, -0.45 if k % 2 else 0.45, level)
    k += 1
    x += step

# 16–18.6: riser. Noise and a sine sweep, filter opening, ends on the cut.
rise_len = 2.6
t = T(rise_len)
k = t / rise_len
nz = tv_filter(noise(rise_len), lambda tt, f: np.exp(-((np.log(f + 1) - np.log(200 + 5800 * (tt / rise_len) ** 2.2)) ** 2) / 0.5))
sw = sine_sweep(rise_len, hz('D3'), hz('D5'), 'exp') * 0.5 + sine_sweep(rise_len, hz('A3'), hz('A5'), 'exp') * 0.3
riser = (nz / (np.abs(nz).max() + 1e-9) * 0.8 + sw) * (0.08 + 0.92 * k ** 2.0)
place(music, riser, 16.0, 0, 0.42)

# 18.8: one low piano-like D3, long room.
def piano(f0, sec=1.25):
    t = T(sec)
    B = 0.00035
    out = np.zeros(len(t))
    for n in range(1, 18):
        fn = n * f0 * np.sqrt(1 + B * n * n)
        amp = (1 / n ** 1.15) * (1 if n < 8 else 0.6)
        d1, d2 = 0.18 / (1 + 0.25 * n), 2.2 / (1 + 0.3 * n)
        e = 0.55 * np.exp(-t / d1) + 0.45 * np.exp(-t / d2)
        for c in (-0.35, 0.0, 0.35):  # three strings, a few cents apart
            out += amp * e * np.sin(2 * np.pi * fn * 2 ** (c / 1200) * t + rng.random() * 6.28) / 3
    hammer = lp(noise(sec), 2500, 2) * np.exp(-t / 0.006) * 0.4
    return (out + hammer) * env_ar(len(t), 0.002, 0.12)


note = piano(hz('D3'), 1.2)
note_st = np.stack([note, note], axis=1)
note_st = reverb(note_st, ir(2.6, 0.7, 5000, 3), 0.35)[: int(1.2 * SR)]
note_st *= env_ar(len(note_st), 0.001, 0.25)[:, None]
final_note = stereo()
place(final_note, note_st, 18.8, 0, 0.2)

# Room for the music (not the final note): small, cold.
music = reverb(music, ir(1.6, 0.35, 6000, 5), 0.18)[:N]


# ---------- sound effects ----------

sfx = stereo()

# Prompt: soft glass key ticks while it types.
x = EV['promptType'][0]
while x < EV['promptType'][1]:
    t = T(0.06)
    tick = bp(noise(0.06), 2800, 7000, 2) * np.exp(-t / 0.004) + 0.3 * np.sin(2 * np.pi * 2300 * t) * np.exp(-t / 0.012)
    place(sfx, tick, x, 0.15 + rng.uniform(-0.1, 0.1), 0.05 * rng.uniform(0.6, 1.0))
    x += rng.uniform(0.035, 0.065)

# Card lifted off the report: suction release, then air.
t = T(0.25)
thup = lp(noise(0.25), 600, 2) * np.exp(-t / 0.03) + 0.6 * np.sin(2 * np.pi * (90 + 220 * t) * t) * np.exp(-t / 0.05)
place(sfx, thup, 0.98, -0.2, 0.32)
a0, a1 = EV['cardLift']
air = bp(noise(a1 - a0 + 0.3), 400, 2500, 2)
air *= env_ar(len(air), 0.25, 0.35, 1.5)
place(sfx, air, a0, -0.1, 0.06)

# Paper settling, faint.
def rustle(sec, density=60, lo=1500, hi=9000):
    n = int(round(sec * SR))
    out = np.zeros(n)
    k = int(density * sec)
    for _ in range(k):
        i = rng.integers(0, max(1, n - 800))
        L = rng.integers(80, 700)
        out[i:i + L] += rng.standard_normal(L) * np.exp(-np.arange(L) / (L / 4)) * rng.uniform(0.3, 1)
    return bp(out + 0.15 * rng.standard_normal(n), lo, hi, 2)


r_ = rustle(0.7, 40)
place(sfx, r_ * env_ar(len(r_), 0.1, 0.3), 1.2, 0.05, 0.05)

# Pen on paper, following the stroke's speed.
e0, e1 = EV['ellipse']
sec = e1 - e0 + 0.05
t = T(sec)
speed = np.gradient(smoother(t / (e1 - e0))) * SR * (e1 - e0)
scratch = bp(noise(sec), 2200, 9000, 2) * (0.35 + speed) + 0.6 * rustle(sec, 220, 2500, 10000)
scratch *= env_ar(len(t), 0.02, 0.06)
place(sfx, scratch, e0, 0.25, 0.035)
c_ = bp(noise(0.03), 1500, 6000, 2)
place(sfx, c_ * env_ar(len(c_), 0.001, 0.02), EV['penIn'][1], 0.25, 0.08)

# Report dragged away.
d0, d1 = EV['reportOut']
sec = d1 - d0
drag = lp(noise(sec), 2800, 2) * np.sin(np.pi * np.clip(T(sec) / sec, 0, 1)) ** 1.5 + 0.4 * rustle(sec, 80, 800, 6000)
place(sfx, drag, d0, -0.5, 0.07)

# Grippers and servos: short whirs as the arms move.
def whir(sec, f0, f1, level=1.0):
    t = T(sec)
    f = f0 + (f1 - f0) * smoother(t / sec)
    ph = 2 * np.pi * np.cumsum(f) / SR
    s = 0.6 * np.sin(ph) + 0.25 * np.sin(2 * ph) + 0.15 * np.sin(3.01 * ph)
    s = lp(s + 0.05 * rng.standard_normal(len(t)), 1800, 2)
    return s * env_ar(len(t), 0.04, 0.08) * level


place(sfx, whir(0.33, 420, 610), 0.62, -0.6, 0.035)
place(sfx, whir(0.2, 380, 300), 0.86, -0.6, 0.03)
place(sfx, whir(0.25, 500, 650), EV['penIn'][0], 0.6, 0.03)
place(sfx, whir(0.25, 650, 480), EV['penOut'][0], 0.6, 0.03)
place(sfx, whir(0.3, 360, 520), 2.45, -0.6, 0.03)
place(sfx, whir(0.4, 300, 560), 8.75, -0.7, 0.035)

# Spheres: three rolls, then the three tinks D–A–F.
s0 = EV['sphereRoll'][0]
settle = EV['sphereSettle']
for i, (arrive, pan) in enumerate(zip(settle, [0.0, -0.45, 0.45])):
    start = s0 + i * 0.06
    sec = arrive - start + 0.05
    t = T(sec)
    k = t / sec
    rot = 9 * (1 - k) + 2  # rolling rate falls as it slows
    rum = lp(noise(sec), 320, 2) * (0.6 + 0.4 * np.sin(2 * np.pi * np.cumsum(rot) / SR)) * (1 - k) ** 0.6
    rum += 0.3 * bp(noise(sec), 1200, 3500, 2) * (1 - k) ** 2
    place(sfx, rum * env_ar(len(t), 0.08, 0.04), start, pan, 0.12)


def tink(f, dec=0.45):
    t = T(1.0)
    s = np.zeros(len(t))
    for r, a, d in [(1, 1.0, 1.0), (2.76, 0.5, 0.55), (5.40, 0.28, 0.32), (8.93, 0.16, 0.2)]:
        s += a * np.sin(2 * np.pi * f * r * t) * np.exp(-t / (dec * d))
    s += bp(noise(1.0), 4000, 12000, 2) * np.exp(-t / 0.002) * 0.6
    return s * env_ar(len(t), 0.0005, 0.1)


for at, name, pan in zip(settle, ['D6', 'A6', 'F6'], [0.0, -0.45, 0.45]):
    place(sfx, tink(hz(name)), at, pan, 0.11)

# Magnetic shimmer: band-passed noise rising, a faint high tone, filings crackling in.
f0_, f1_ = EV['fieldLines'][0], 6.0
sec = f1_ - f0_
sh = tv_filter(noise(sec), lambda tt, f: np.exp(-((np.log(f + 1) - np.log(500 + 3500 * (tt / sec))) ** 2) / 0.08))
t = T(sec)
sh = sh / (np.abs(sh).max() + 1e-9) * np.sin(np.pi * np.clip(t / sec, 0, 1)) ** 1.2
tone = np.sin(2 * np.pi * 3520 * t) * (0.5 + 0.5 * np.sin(2 * np.pi * 5.5 * t)) * np.sin(np.pi * t / sec) ** 2 * 0.15
crk = np.zeros(len(t))
fl0, fl1 = EV['filings']
for _ in range(900):
    u = rng.random()
    at = (fl0 - f0_) + (fl1 - fl0) * u ** 0.7
    i = int(at * SR)
    if 0 <= i < len(t) - 60:
        crk[i:i + 60] += rng.standard_normal(60) * np.exp(-np.arange(60) / 8) * rng.uniform(0.2, 1)
crk = hp(crk, 3000, 2)
shimmer = np.stack([sh * 0.9 + crk * 0.55 + tone, sh * 0.9 + np.roll(crk, 37) * 0.55 + tone], axis=1)
place(sfx, shimmer, f0_, 0, 0.22)

# Spheres rolling apart, softer.
a0, a1 = EV['spheresApart']
for i, pan in enumerate([0.0, -0.6, 0.6]):
    sec = a1 - a0
    t = T(sec)
    rum = lp(noise(sec), 280, 2) * np.sin(np.pi * t / sec) ** 2
    place(sfx, rum, a0 + i * 0.03, pan, 0.06)

# The light sweeping across the sheet, left to right.
x0, x1 = EV['exposure']
sec = x1 - x0 + 0.2
t = T(sec)
sweep = hp(noise(sec), 1800, 2) * np.sin(np.pi * np.clip(t / sec, 0, 1)) ** 2
panv = -0.8 + 1.6 * smoother(t / sec)
ang = (panv + 1) * np.pi / 4
place(sfx, np.stack([sweep * np.cos(ang), sweep * np.sin(ang)], axis=1), x0 - 0.1, 0, 0.07)

# 6–9: the three bodies at work. Arm servo with the pick-and-place loop,
# quadruped footfalls with its gait, the drone's rotors.
b0, b1 = 6.4, 9.0
sec = b1 - b0
t = T(sec)
fade = env_ar(len(t), 0.5, 0.4)
u = (t + b0 - 6.8) * 0.62 * 2 * np.pi
armf = 420 + 160 * np.abs(np.cos(u))
ph = 2 * np.pi * np.cumsum(armf) / SR
arm = lp(0.6 * np.sin(ph) + 0.3 * np.sin(2 * ph), 1500, 2) * (0.4 + 0.6 * np.abs(np.cos(u)))
place(sfx, arm * fade, b0, -0.6, 0.05)
steps = stereo()
x = 6.8
while x < 9.0:
    for off in (0.0, 0.36):
        st = lp(noise(0.08), 900, 2) * np.exp(-T(0.08) / 0.012)
        place(steps, st, x + off, 0.0, 0.12)
    x += 0.72
sfx += steps
rot = np.zeros(len(t))
for k2, f in enumerate([182, 185.5, 188, 191]):
    rot += np.sin(2 * np.pi * f * t + k2) + 0.4 * np.sin(2 * np.pi * 2 * f * t)
rot = lp(rot, 1200, 2) * (0.85 + 0.15 * np.sin(2 * np.pi * 0.55 * t)) + 0.4 * bp(noise(sec), 300, 1200, 2)
place(sfx, rot * fade, b0, 0.6, 0.04)

# Glass disc pushed across: low friction that follows its speed, a crystalline ring.
g0, g1 = EV['glassSlide']
sec = g1 - g0
t = T(sec)
k = t / sec
spd = np.gradient(np.where(k < 0.5, 4 * k ** 3, 1 - (-2 * k + 2) ** 3 / 2)) * SR * sec
fr = lp(noise(sec), 1400, 2) * (0.2 + spd) * 0.6 + bp(noise(sec), 180, 500, 2) * spd * 0.5
ring = (np.sin(2 * np.pi * 2637 * t) + 0.6 * np.sin(2 * np.pi * 3951 * t + 1) + 0.35 * np.sin(2 * np.pi * 5274 * t)) * (0.6 + 0.4 * np.sin(2 * np.pi * 3.1 * t)) * np.sin(np.pi * k) ** 2 * 0.25
glass = (fr + ring) * env_ar(len(t), 0.05, 0.1)
panv = -0.8 + 1.6 * k
ang = (panv + 1) * np.pi / 4
place(sfx, np.stack([glass * np.cos(ang), glass * np.sin(ang)], axis=1), g0, 0, 0.3)

# The stamp: a thud that drops 120 -> 40 Hz, a paper slap, a short room.
imp = EV['stampImpact']
t = T(0.7)
fdrop = 40 + 80 * np.exp(-t / 0.04)
th = np.sin(2 * np.pi * np.cumsum(fdrop) / SR) * np.exp(-t / 0.13)
slap = hp(noise(0.7), 900, 2) * np.exp(-t / 0.008) * 0.7
thud = np.stack([th + slap, th + slap], axis=1)
thud = reverb(thud, ir(0.45, 0.09, 4000, 9), 0.25)[: len(t)]
place(sfx, thud, imp, 0, 0.55)
# The stamp pulled off the page: a short tacky lift.
l0, l1 = EV['stampLift']
t = T(l1 - l0)
tack = bp(noise(l1 - l0), 600, 3500, 2) * np.exp(-t / 0.025) + 0.3 * np.sin(2 * np.pi * (300 + 900 * t) * t) * np.exp(-t / 0.03)
place(sfx, tack, l0, 0.1, 0.12)
# Glove sliding off the page.
o0, o1 = EV['gloveOut']
sec = o1 - o0
t = T(sec)
brush = bp(noise(sec), 300, 2200, 2) * np.sin(np.pi * t / sec) ** 1.5 + 0.3 * rustle(sec, 50, 600, 4000)
place(sfx, brush, o0, -0.6, 0.06)

# 12–16: each card lands. A soft card slap and a blip climbing D minor.
scale = ['D5', 'E5', 'F5', 'G5', 'A5', 'Bb5', 'C6', 'D6', 'E6', 'F6', 'G6', 'A6']
for i, ft in enumerate(flashes):
    t = T(0.25)
    sl = bp(noise(0.25), 600, 3200, 2) * np.exp(-t / 0.012)
    blip = np.sin(2 * np.pi * hz(scale[i]) * t) * np.exp(-t / 0.045) * env_ar(len(t), 0.001, 0.02)
    place(sfx, sl, ft, 0.15, 0.42)
    place(sfx, blip, ft, 0.15 * (-1) ** i, 0.22)
    # The card's fall just before it lands: a short swish.
    fall = min(0.12, 0.42 * (TL['flashes']['frames'][i] / TL['meta']['fps']))
    fs = bp(noise(fall), 1500, 6000, 2) * np.linspace(0, 1, int(round(fall * SR))) ** 2
    place(sfx, fs, ft - fall, 0.1, 0.07)

# 16–18.6: everything pulled into the point; a heavy relay clunk at the cut.
c0, c1 = EV['converge']
sec = c1 - c0
t = T(sec)
k = t / sec
suck = tv_filter(noise(sec), lambda tt, f: 1 / (1 + (f / (150 + 5000 * (tt / sec) ** 3)) ** 2))
suck = suck / (np.abs(suck).max() + 1e-9) * k ** 3
sub = np.sin(2 * np.pi * np.cumsum(30 + 50 * k ** 2) / SR) * k ** 2
place(sfx, suck * 0.9 + sub * 0.5, c0, 0, 0.3)
flare = EV['flare'][0]
t = T(0.035)
click = hp(noise(0.035), 1200, 2) * np.exp(-t / 0.003)
body = np.sin(2 * np.pi * 62 * t) * np.exp(-t / 0.02) + 0.5 * np.sin(2 * np.pi * 130 * t) * np.exp(-t / 0.01)
clunk = click * 0.8 + body
place(sfx, clunk, flare - 0.012, 0, 0.9)
place(sfx, hp(noise(0.006), 2000, 2), flare + 0.008, 0, 0.25)  # the contact's second bounce


# ---------- rules, mix, loudness ----------

def cut_after(x, t_cut):
    """Nothing rings past the cut: hard gate with a 1 ms fade."""
    i = int(round(t_cut * SR))
    f = int(0.001 * SR)
    x[i - f:i] *= np.linspace(1, 0, f)[:, None]
    x[i:] = 0
    return x


black0, black1 = EV['black']
music = cut_after(music, black0)
sfx = cut_after(sfx, black0)
music += final_note
music[int(round(black0 * SR)):int(round(black1 * SR))] = 0
sfx[int(round(black0 * SR)):int(round(black1 * SR))] = 0

SFX_OVER_MUSIC_DB = 2.5
sfx *= 10 ** (SFX_OVER_MUSIC_DB / 20)
mix = music + sfx
music = hp(music, 20, 2)
sfx = hp(sfx, 20, 2)
mix = music + sfx

meter = pyln.Meter(SR)
gain_db = TL['audio']['loudness']['integratedLUFS'] - meter.integrated_loudness(mix)
for _ in range(4):
    # Normalise, limit the true peak, re-measure (the limiter costs a little loudness).
    g = 10 ** (gain_db / 20)
    m = mix * g
    ceiling = 10 ** (TL['audio']['loudness']['truePeakDBTP'] / 20) * 0.94
    over = np.abs(resample_poly(m, 4, 1, axis=0)).max(axis=1)
    over = np.maximum(over.reshape(-1, 4).max(axis=1), 1e-9)
    gr = np.minimum(1, ceiling / over)
    # Look-ahead: 1.5 ms attack, 60 ms release, so the limiter never clicks.
    la = int(0.0015 * SR)
    gr = np.lib.stride_tricks.sliding_window_view(np.pad(gr, (0, la), constant_values=1), la + 1).min(axis=1)
    rel = np.exp(-1 / (0.06 * SR))
    sm = np.empty_like(gr)
    cur = 1.0
    for i, v in enumerate(gr):
        cur = v if v < cur else v + (cur - v) * rel
        sm[i] = cur
    limited = m * sm[:, None]
    lufs = meter.integrated_loudness(limited)
    if abs(lufs - TL['audio']['loudness']['integratedLUFS']) < 0.1:
        break
    gain_db += TL['audio']['loudness']['integratedLUFS'] - lufs

tp = 20 * np.log10(np.abs(resample_poly(limited, 4, 1, axis=0)).max())
g = 10 ** (gain_db / 20)
# Re-impose the silences exactly (true digital zeros).
for buf in (limited,):
    buf[int(round(black0 * SR)):int(round(black1 * SR))] = 0

out = os.path.join(ROOT, 'out', 'audio')
os.makedirs(out, exist_ok=True)
sf.write(os.path.join(out, 'music.wav'), music * g, SR, subtype='PCM_24')
sf.write(os.path.join(out, 'sfx.wav'), sfx * g, SR, subtype='PCM_24')
sf.write(os.path.join(out, 'mix.wav'), limited, SR, subtype='PCM_24')
print(f'mix: {meter.integrated_loudness(limited):.2f} LUFS integrated, true peak {tp:.2f} dBTP, gain {gain_db:+.1f} dB')
